export 'announcements/announcements_repository.dart';
export 'historical_artistic_landmarks/historical_artistic_landmarks_repository.dart';
export 'academic_buildings/academic_buildings_repository.dart';
export 'admin_buildings/admin_buildings_repository.dart';
export 'campus_life/campus_life_repository.dart';
export 'colleges/colleges_repository.dart';
export 'facilities_amenities/facilities_amenities_repository.dart';
export 'messages/messages_repository.dart';
export 'organizations/organizations_repository.dart';
